export const ROUTES = {
  HOME: "/",
  TOUR: "/diem-den",
  CREATETOUR: "/tao-tour-du-lich",
  PAY: "/pay/:id",
  TOURALL: "/tour",
  HDVALL: "/hdv",
  DULICH: "/du-lich/:id",
  PERSONAL: "/trang-ca-nhan",
  NEWS: "/tin-tuc",
  INTRODUCE: "/gioi-thieu",
  TOURDETAIL: "/tour/:id",
  NEWSDETAIL: "/tin-tuc/:id",
  MYTRIP: "/chuyen-di",
  SIGNIN: "/dang-nhap",
  SIGNUP: "/dang-ky",
  ONBOARDING: "/onboarding",
  CHAT: "/chat",
  NEWPOST: "viet-bai",
};
