export const ROUTES = {
  HOME: "/",
  TOUR: "/diem-den",
  CREATETOUR: "/tao-tour-du-lich",
  PAY: "/pay",
  TOURALL: "/tour",
  HDVALL: "/hdv",
  DULICH: "/du-lich/:id",
  PERSONAL: "/trang-ca-nhan/:id",
  NEWS: "/tin-tuc",
  INTRODUCE: "/gioi-thieu",
  TOURDETAIL: "/tour/:id",
  NEWSDETAIL: "/tin-tuc/:id",
  MYTRIP: "/chuyen-di",
  SIGNIN: "/dang-nhap",
  SIGNUP: "/dang-ky",
  ONBOARDING: "/onboarding",
  CHAT: "/chat",
  NEWPOST: "/viet-bai",
  LISTPOST: "/me/posts",
  SETTING: "/account",
  MYPAGE: "/kenh-hdv",
  ADDTOUR: "/kenh-hdv/them-tour",
  DOANHTHU: "/kenh-hdv/doanh-thu",
  BANKACC: "/kenh-hdv/tai-khoan",
  // ADDVOUCHER: "/kenh-hdv/create-voucher",
  QLVOUCHER: "/kenh-hdv/voucher",
  DSTOUR: "/kenh-hdv/ds-tour",
  THIETLAP: "/kenh-hdv/setting",
  DANHGIA: "/kenh-hdv/danh-gia-tour",
  DONHANG: "/kenh-hdv/don-hang",
  TIMKIEMTOUR: "/chuyen-di/:id",
  QUENMATKHAU: "/quen-mat-khau",
  CHITIETTOUR: "/kenh-hdv/chi-tiet-tour/:id",
  CHITIETORDER: "/kenh-hdv/chi-tiet-don/:id",
  ACTIVETK: "/active-user/:id",
  UPDATEPAY: "/update-pay",
};
